;[
  {
    path: { full: '/META-INF/container.xml', file: '/META-INF/' },
    filename: 'container.xml',
    ext: '.xml',
    size: 266,
    dirname: 'META-INF',
  },
  {
    path: { full: '/mimetype', file: '/' },
    filename: 'mimetype',
    ext: null,
    size: 20,
    dirname: 'test',
  },
  {
    path: { full: '/OEBPS/content.opf', file: '/OEBPS/' },
    filename: 'content.opf',
    ext: '.opf',
    size: 10872,
    dirname: 'OEBPS',
  },
  {
    path: { full: '/OEBPS/css/epub3.css', file: '/OEBPS/css/' },
    filename: 'epub3.css',
    ext: '.css',
    size: 1636,
    dirname: 'css',
  },
  {
    path: { full: '/OEBPS/css/idGeneratedStyles.css', file: '/OEBPS/css/' },
    filename: 'idGeneratedStyles.css',
    ext: '.css',
    size: 8268,
    dirname: 'css',
  },
  {
    path: { full: '/OEBPS/font/ACaslonPro-Bold.otf', file: '/OEBPS/font/' },
    filename: 'ACaslonPro-Bold.otf',
    ext: '.otf',
    size: 142972,
    dirname: 'font',
  },
  {
    path: { full: '/OEBPS/font/ACaslonPro-Italic.otf', file: '/OEBPS/font/' },
    filename: 'ACaslonPro-Italic.otf',
    ext: '.otf',
    size: 167264,
    dirname: 'font',
  },
  {
    path: {
      full: '/OEBPS/font/ACaslonPro-Regular.otf',
      file: '/OEBPS/font/',
    },
    filename: 'ACaslonPro-Regular.otf',
    ext: '.otf',
    size: 161820,
    dirname: 'font',
  },
  {
    path: {
      full: '/OEBPS/font/ACaslonPro-Semibold.otf',
      file: '/OEBPS/font/',
    },
    filename: 'ACaslonPro-Semibold.otf',
    ext: '.otf',
    size: 165956,
    dirname: 'font',
  },
  {
    path: {
      full: '/OEBPS/font/ACaslonPro-SemiboldItalic.otf',
      file: '/OEBPS/font/',
    },
    filename: 'ACaslonPro-SemiboldItalic.otf',
    ext: '.otf',
    size: 170172,
    dirname: 'font',
  },
  {
    path: {
      full: '/OEBPS/font/AGaramondPro-Semibold.otf',
      file: '/OEBPS/font/',
    },
    filename: 'AGaramondPro-Semibold.otf',
    ext: '.otf',
    size: 95648,
    dirname: 'font',
  },
  {
    path: {
      full: '/OEBPS/font/Canterbury-Regular.ttf',
      file: '/OEBPS/font/',
    },
    filename: 'Canterbury-Regular.ttf',
    ext: '.ttf',
    size: 51256,
    dirname: 'font',
  },
  {
    path: { full: '/OEBPS/font/RotisSemiSerif.otf', file: '/OEBPS/font/' },
    filename: 'RotisSemiSerif.otf',
    ext: '.otf',
    size: 23116,
    dirname: 'font',
  },
  {
    path: { full: '/OEBPS/font/SBLGreek.ttf', file: '/OEBPS/font/' },
    filename: 'SBLGreek.ttf',
    ext: '.ttf',
    size: 1123080,
    dirname: 'font',
  },
  {
    path: { full: '/OEBPS/font/SBLHebrew.ttf', file: '/OEBPS/font/' },
    filename: 'SBLHebrew.ttf',
    ext: '.ttf',
    size: 314992,
    dirname: 'font',
  },
  {
    path: { full: '/OEBPS/font/TimesNewRomanPSMT.ttf', file: '/OEBPS/font/' },
    filename: 'TimesNewRomanPSMT.ttf',
    ext: '.ttf',
    size: 836380,
    dirname: 'font',
  },
  {
    path: { full: '/OEBPS/font/ZapfDingbats.ttf', file: '/OEBPS/font/' },
    filename: 'ZapfDingbats.ttf',
    ext: '.ttf',
    size: 156088,
    dirname: 'font',
  },
  {
    path: { full: '/OEBPS/img/Cover.jpg', file: '/OEBPS/img/' },
    filename: 'Cover.jpg',
    ext: '.jpg',
    size: 579265,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page004.png', file: '/OEBPS/img/' },
    filename: 'page004.png',
    ext: '.png',
    size: 55960,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page026.png', file: '/OEBPS/img/' },
    filename: 'page026.png',
    ext: '.png',
    size: 78120,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page032.png', file: '/OEBPS/img/' },
    filename: 'page032.png',
    ext: '.png',
    size: 335466,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page047.png', file: '/OEBPS/img/' },
    filename: 'page047.png',
    ext: '.png',
    size: 109225,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page053.png', file: '/OEBPS/img/' },
    filename: 'page053.png',
    ext: '.png',
    size: 806009,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page063.png', file: '/OEBPS/img/' },
    filename: 'page063.png',
    ext: '.png',
    size: 1615108,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page070.png', file: '/OEBPS/img/' },
    filename: 'page070.png',
    ext: '.png',
    size: 1289923,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page079.png', file: '/OEBPS/img/' },
    filename: 'page079.png',
    ext: '.png',
    size: 1279474,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page095.png', file: '/OEBPS/img/' },
    filename: 'page095.png',
    ext: '.png',
    size: 1010688,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page184.png', file: '/OEBPS/img/' },
    filename: 'page184.png',
    ext: '.png',
    size: 28355,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page186.png', file: '/OEBPS/img/' },
    filename: 'page186.png',
    ext: '.png',
    size: 63866,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page192.png', file: '/OEBPS/img/' },
    filename: 'page192.png',
    ext: '.png',
    size: 98936,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page224.png', file: '/OEBPS/img/' },
    filename: 'page224.png',
    ext: '.png',
    size: 114986,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page243.png', file: '/OEBPS/img/' },
    filename: 'page243.png',
    ext: '.png',
    size: 85931,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page257.png', file: '/OEBPS/img/' },
    filename: 'page257.png',
    ext: '.png',
    size: 92195,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page271.png', file: '/OEBPS/img/' },
    filename: 'page271.png',
    ext: '.png',
    size: 149749,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page298.png', file: '/OEBPS/img/' },
    filename: 'page298.png',
    ext: '.png',
    size: 84612,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page306.png', file: '/OEBPS/img/' },
    filename: 'page306.png',
    ext: '.png',
    size: 134078,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page311.png', file: '/OEBPS/img/' },
    filename: 'page311.png',
    ext: '.png',
    size: 116766,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page357.png', file: '/OEBPS/img/' },
    filename: 'page357.png',
    ext: '.png',
    size: 126573,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page367.png', file: '/OEBPS/img/' },
    filename: 'page367.png',
    ext: '.png',
    size: 63963,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page369.png', file: '/OEBPS/img/' },
    filename: 'page369.png',
    ext: '.png',
    size: 60748,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page375.png', file: '/OEBPS/img/' },
    filename: 'page375.png',
    ext: '.png',
    size: 86906,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page395.png', file: '/OEBPS/img/' },
    filename: 'page395.png',
    ext: '.png',
    size: 70354,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page416.png', file: '/OEBPS/img/' },
    filename: 'page416.png',
    ext: '.png',
    size: 89751,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page432.png', file: '/OEBPS/img/' },
    filename: 'page432.png',
    ext: '.png',
    size: 113280,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page455.png', file: '/OEBPS/img/' },
    filename: 'page455.png',
    ext: '.png',
    size: 120993,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page485.png', file: '/OEBPS/img/' },
    filename: 'page485.png',
    ext: '.png',
    size: 256630,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page531.png', file: '/OEBPS/img/' },
    filename: 'page531.png',
    ext: '.png',
    size: 175077,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page557.png', file: '/OEBPS/img/' },
    filename: 'page557.png',
    ext: '.png',
    size: 48353,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page575.png', file: '/OEBPS/img/' },
    filename: 'page575.png',
    ext: '.png',
    size: 251773,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page585.png', file: '/OEBPS/img/' },
    filename: 'page585.png',
    ext: '.png',
    size: 60343,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page592.png', file: '/OEBPS/img/' },
    filename: 'page592.png',
    ext: '.png',
    size: 100923,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page615.png', file: '/OEBPS/img/' },
    filename: 'page615.png',
    ext: '.png',
    size: 108806,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page626.png', file: '/OEBPS/img/' },
    filename: 'page626.png',
    ext: '.png',
    size: 51593,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page653.png', file: '/OEBPS/img/' },
    filename: 'page653.png',
    ext: '.png',
    size: 910768,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page703.png', file: '/OEBPS/img/' },
    filename: 'page703.png',
    ext: '.png',
    size: 73825,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page718.png', file: '/OEBPS/img/' },
    filename: 'page718.png',
    ext: '.png',
    size: 257574,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page732.png', file: '/OEBPS/img/' },
    filename: 'page732.png',
    ext: '.png',
    size: 124873,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page742.png', file: '/OEBPS/img/' },
    filename: 'page742.png',
    ext: '.png',
    size: 1353415,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page752.png', file: '/OEBPS/img/' },
    filename: 'page752.png',
    ext: '.png',
    size: 31077,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page753.png', file: '/OEBPS/img/' },
    filename: 'page753.png',
    ext: '.png',
    size: 91986,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page783.png', file: '/OEBPS/img/' },
    filename: 'page783.png',
    ext: '.png',
    size: 88451,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/page790.png', file: '/OEBPS/img/' },
    filename: 'page790.png',
    ext: '.png',
    size: 57079,
    dirname: 'img',
  },
  {
    path: { full: '/OEBPS/img/titlepage.png', file: '/OEBPS/img/' },
    filename: 'titlepage.png',
    ext: '.png',
    size: 40693,
    dirname: 'img',
  },
  {
    path: {
      full: '/OEBPS/text/PP01_frontmatter01.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP01_frontmatter01.xhtml',
    ext: '.xhtml',
    size: 6287,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP01_frontmatter02.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP01_frontmatter02.xhtml',
    ext: '.xhtml',
    size: 621,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP01_frontmatter03.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP01_frontmatter03.xhtml',
    ext: '.xhtml',
    size: 1931,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP01_frontmatter04.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP01_frontmatter04.xhtml',
    ext: '.xhtml',
    size: 815,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP01_frontmatter05.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP01_frontmatter05.xhtml',
    ext: '.xhtml',
    size: 15226,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP01_frontmatter06.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP01_frontmatter06.xhtml',
    ext: '.xhtml',
    size: 9015,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP01_frontmatter07.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP01_frontmatter07.xhtml',
    ext: '.xhtml',
    size: 14147,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter01.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter01.xhtml',
    ext: '.xhtml',
    size: 312851,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter02.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter02.xhtml',
    ext: '.xhtml',
    size: 187221,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter03.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter03.xhtml',
    ext: '.xhtml',
    size: 102408,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter04.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter04.xhtml',
    ext: '.xhtml',
    size: 97977,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter05.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter05.xhtml',
    ext: '.xhtml',
    size: 314455,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter06.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter06.xhtml',
    ext: '.xhtml',
    size: 182352,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter07.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter07.xhtml',
    ext: '.xhtml',
    size: 319342,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter08.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter08.xhtml',
    ext: '.xhtml',
    size: 199270,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter09.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter09.xhtml',
    ext: '.xhtml',
    size: 101608,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter10.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter10.xhtml',
    ext: '.xhtml',
    size: 155507,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter11.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter11.xhtml',
    ext: '.xhtml',
    size: 96422,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter12.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter12.xhtml',
    ext: '.xhtml',
    size: 49949,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter13.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter13.xhtml',
    ext: '.xhtml',
    size: 52762,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter14.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter14.xhtml',
    ext: '.xhtml',
    size: 87429,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/text/PP02_chapter15.xhtml', file: '/OEBPS/text/' },
    filename: 'PP02_chapter15.xhtml',
    ext: '.xhtml',
    size: 255181,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP03_backmatter01.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP03_backmatter01.xhtml',
    ext: '.xhtml',
    size: 430977,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP03_backmatter02.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP03_backmatter02.xhtml',
    ext: '.xhtml',
    size: 95474,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP03_backmatter03.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP03_backmatter03.xhtml',
    ext: '.xhtml',
    size: 724849,
    dirname: 'text',
  },
  {
    path: {
      full: '/OEBPS/text/PP03_backmatter04.xhtml',
      file: '/OEBPS/text/',
    },
    filename: 'PP03_backmatter04.xhtml',
    ext: '.xhtml',
    size: 939430,
    dirname: 'text',
  },
  {
    path: { full: '/OEBPS/toc.ncx', file: '/OEBPS/' },
    filename: 'toc.ncx',
    ext: '.ncx',
    size: 7526,
    dirname: 'OEBPS',
  },
  {
    path: { full: '/OEBPS/toc.xhtml', file: '/OEBPS/' },
    filename: 'toc.xhtml',
    ext: '.xhtml',
    size: 72059,
    dirname: 'OEBPS',
  },
]
